### PR TITLE
Beta

### PR DESCRIPTION
**Pull request by Altansar69**
Reply button 
+ commit of redpoint (idk what is it)

close issues #67

### CODE REVIEW

**Comment by Altansar69** [comment]
close #70

**Comment by Altansar69** [comment]
Nice, gj. Now we just need subero for review

**Comment by SubZeroPL** [comment]
Sorry, i was offline for last weeks, i'll try to take a look soon.

**Review by SubZeroPL — CHANGES_REQUESTED** [review]
Looks fine, just one small issue, great job :)

**Comment by Altansar69** [comment]
> Looks fine, just one small issue, great job :)

Reddiepoint works too hard 😆

**Review by SubZeroPL — APPROVED** [review]

**Pull request merged**
