### PR TITLE
mini shoutbox + close 2 issues

### PR DESCRIPTION
**Pull request by Altansar69**
addition of a mini shoutbox thanks to Redpoint
Added post reply button for close issues https://github.com/SubZeroPL/cs-rin-ru-enhanced-mod/issues/2
Hide SCS on not hide by default for close issues https://github.com/SubZeroPL/cs-rin-ru-enhanced-mod/issues/15

### CODE REVIEW

**Comment by Reddiepoint** [comment]
Hello there. You definitely improved my code a lot :)

**Comment by Altansar69** [comment]
you did it all ;)

**Comment by Altansar69** [comment]
the title of the sweater is no longer really up to date as there have been other commits in the meantime.
if you accept the merger, you can close:
https://github.com/SubZeroPL/cs-rin-ru-enhanced-mod/issues/20
https://github.com/SubZeroPL/cs-rin-ru-enhanced-mod/issues/15
https://github.com/SubZeroPL/cs-rin-ru-enhanced-mod/issues/7
https://github.com/SubZeroPL/cs-rin-ru-enhanced-mod/issues/6
https://github.com/SubZeroPL/cs-rin-ru-enhanced-mod/issues/3
https://github.com/SubZeroPL/cs-rin-ru-enhanced-mod/issues/2

**Comment by SubZeroPL** [comment]
Man, you are a robot :D Thanks a lot. Sorry, I've been a bit sick last days, I'll review and merge as soon as I can.

**Comment by Altansar69** [comment]
Redpoint has helped a lot ;).
No worries it's not hurried in any case. Take your time

**Comment by Altansar69** [comment]
oh and for the version numbers. I don't know what to put on each version, I put a bit of a random number to be honest xD

**Comment by SubZeroPL** [comment]
Well mostly it depends on what was done. Last number is mostly for error fixes or very minor modifications, second from right is for bigger bugfixes or new features, and the leftmost would be set to 1 when the script is complete and no new features need to be added (which I assume would be never 😛 )

**Comment by Altansar69** [comment]
oh right, thanks for the information.
I've just added a commit that changes a lot of things. Once again, it was only possible thanks to Repoint's help.
You can now close the issues https://github.com/SubZeroPL/cs-rin-ru-enhanced-mod/issues/9
A solution was also found to really resolve the issue https://github.com/SubZeroPL/cs-rin-ru-enhanced-mod/issues/10

**Comment by Altansar69** [comment]
we need confirmation from Ressourector, but I think we can do away with the warning message for dynamic functions

**Comment by SubZeroPL** [comment]
So are you working on something still or can we merge it?

**Review by SubZeroPL — APPROVED** [review]

**Comment by Altansar69** [comment]
thx for the merge. Can you also close issues https://github.com/SubZeroPL/cs-rin-ru-enhanced-mod/issues/9 and https://github.com/SubZeroPL/cs-rin-ru-enhanced-mod/issues/7 plz ?

**Comment by SubZeroPL** [comment]
#7 is kind of open because you can always add more
and why do you want to close #9?

**Comment by SubZeroPL** [comment]
For me it doesn't work. I open any topic with 3 or more pages, go to page 2, scroll down - page 3 is loaded, but then when I scroll up - page 1 is not loading.

**Comment by Reddiepoint** [comment]
In order to load the previous pages, you need to scroll to the top of the page and then scroll upwards even more (approximately 10 clicks of the scroll wheel). This is by design, as to allow the user access to the top of the page without unintentionally loading the previous page.

**Comment by SubZeroPL** [comment]
Great, it really works! Great job @Altansar69 @Reddiepoint! Okay I can close #9

**Pull request merged**
